export const ADD_CAMPAIGNS = "ADD_CAMPAIGNS";
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const REMOVE_CAMPAIGN = "REMOVE_CAMPAIGN";
